web:
  build: .
  dockerfile: Dockerfile
  environment:
    - NODE_ENV=development
    - NODE_PORT=8080
  volumes:
    - .:/src
  ports:
    - "8080:8080"
  links:
    - mongo

mongo:
  image: mongo
  ports:
    - "27017:27017"
